// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtDDVY5SS8G1WOPXSqm0os7nwB8gGk7kc',
    appId: '1:161020575774:web:0b27a13dd73eabd57fee0f',
    messagingSenderId: '161020575774',
    projectId: 'exam-2-flutter',
    authDomain: 'exam-2-flutter.firebaseapp.com',
    storageBucket: 'exam-2-flutter.firebasestorage.app',
    measurementId: 'G-FBH5NGGB0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgzC8lDZikEHCIAkHUUW4zJKdBWVgooXk',
    appId: '1:161020575774:android:1f015f6b859197177fee0f',
    messagingSenderId: '161020575774',
    projectId: 'exam-2-flutter',
    storageBucket: 'exam-2-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsS0g3HHDIDJvIey-mJ9F8rESVS8dyiC0',
    appId: '1:161020575774:ios:33710d0c58ceecf47fee0f',
    messagingSenderId: '161020575774',
    projectId: 'exam-2-flutter',
    storageBucket: 'exam-2-flutter.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsS0g3HHDIDJvIey-mJ9F8rESVS8dyiC0',
    appId: '1:161020575774:ios:33710d0c58ceecf47fee0f',
    messagingSenderId: '161020575774',
    projectId: 'exam-2-flutter',
    storageBucket: 'exam-2-flutter.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtDDVY5SS8G1WOPXSqm0os7nwB8gGk7kc',
    appId: '1:161020575774:web:c81fae6fddc910117fee0f',
    messagingSenderId: '161020575774',
    projectId: 'exam-2-flutter',
    authDomain: 'exam-2-flutter.firebaseapp.com',
    storageBucket: 'exam-2-flutter.firebasestorage.app',
    measurementId: 'G-NF19Y02Y2X',
  );
}
